# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import reservasalas_pb2 as reservasalas__pb2

GRPC_GENERATED_VERSION = '1.64.1'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.65.0'
SCHEDULED_RELEASE_DATE = 'June 25, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in reservasalas_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class ReservaSalasStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CadastrarReserva = channel.unary_unary(
                '/reservassalas.ReservaSalas/CadastrarReserva',
                request_serializer=reservasalas__pb2.ReservaRequest.SerializeToString,
                response_deserializer=reservasalas__pb2.ReservaResponse.FromString,
                _registered_method=True)
        self.RemoverReserva = channel.unary_unary(
                '/reservassalas.ReservaSalas/RemoverReserva',
                request_serializer=reservasalas__pb2.ReservaRequest.SerializeToString,
                response_deserializer=reservasalas__pb2.ReservaResponse.FromString,
                _registered_method=True)
        self.ConsultarReserva = channel.unary_unary(
                '/reservassalas.ReservaSalas/ConsultarReserva',
                request_serializer=reservasalas__pb2.ConsultaRequest.SerializeToString,
                response_deserializer=reservasalas__pb2.ConsultaResponse.FromString,
                _registered_method=True)
        self.ConsultarReservasSala = channel.unary_unary(
                '/reservassalas.ReservaSalas/ConsultarReservasSala',
                request_serializer=reservasalas__pb2.SalaRequest.SerializeToString,
                response_deserializer=reservasalas__pb2.ReservasSalaResponse.FromString,
                _registered_method=True)
        self.ConsultarReservasUsuario = channel.unary_unary(
                '/reservassalas.ReservaSalas/ConsultarReservasUsuario',
                request_serializer=reservasalas__pb2.UsuarioRequest.SerializeToString,
                response_deserializer=reservasalas__pb2.ReservasUsuarioResponse.FromString,
                _registered_method=True)


class ReservaSalasServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CadastrarReserva(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoverReserva(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConsultarReserva(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConsultarReservasSala(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConsultarReservasUsuario(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ReservaSalasServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CadastrarReserva': grpc.unary_unary_rpc_method_handler(
                    servicer.CadastrarReserva,
                    request_deserializer=reservasalas__pb2.ReservaRequest.FromString,
                    response_serializer=reservasalas__pb2.ReservaResponse.SerializeToString,
            ),
            'RemoverReserva': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoverReserva,
                    request_deserializer=reservasalas__pb2.ReservaRequest.FromString,
                    response_serializer=reservasalas__pb2.ReservaResponse.SerializeToString,
            ),
            'ConsultarReserva': grpc.unary_unary_rpc_method_handler(
                    servicer.ConsultarReserva,
                    request_deserializer=reservasalas__pb2.ConsultaRequest.FromString,
                    response_serializer=reservasalas__pb2.ConsultaResponse.SerializeToString,
            ),
            'ConsultarReservasSala': grpc.unary_unary_rpc_method_handler(
                    servicer.ConsultarReservasSala,
                    request_deserializer=reservasalas__pb2.SalaRequest.FromString,
                    response_serializer=reservasalas__pb2.ReservasSalaResponse.SerializeToString,
            ),
            'ConsultarReservasUsuario': grpc.unary_unary_rpc_method_handler(
                    servicer.ConsultarReservasUsuario,
                    request_deserializer=reservasalas__pb2.UsuarioRequest.FromString,
                    response_serializer=reservasalas__pb2.ReservasUsuarioResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'reservassalas.ReservaSalas', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('reservassalas.ReservaSalas', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ReservaSalas(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CadastrarReserva(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/reservassalas.ReservaSalas/CadastrarReserva',
            reservasalas__pb2.ReservaRequest.SerializeToString,
            reservasalas__pb2.ReservaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoverReserva(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/reservassalas.ReservaSalas/RemoverReserva',
            reservasalas__pb2.ReservaRequest.SerializeToString,
            reservasalas__pb2.ReservaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ConsultarReserva(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/reservassalas.ReservaSalas/ConsultarReserva',
            reservasalas__pb2.ConsultaRequest.SerializeToString,
            reservasalas__pb2.ConsultaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ConsultarReservasSala(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/reservassalas.ReservaSalas/ConsultarReservasSala',
            reservasalas__pb2.SalaRequest.SerializeToString,
            reservasalas__pb2.ReservasSalaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ConsultarReservasUsuario(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/reservassalas.ReservaSalas/ConsultarReservasUsuario',
            reservasalas__pb2.UsuarioRequest.SerializeToString,
            reservasalas__pb2.ReservasUsuarioResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
