# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: reservasalas.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12reservasalas.proto\x12\rreservassalas\x1a\x1fgoogle/protobuf/timestamp.proto\"^\n\x0eReservaRequest\x12\x0f\n\x07usuario\x18\x01 \x01(\t\x12\x0c\n\x04sala\x18\x02 \x01(\t\x12-\n\tdata_hora\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"4\n\x0fReservaResponse\x12\x10\n\x08mensagem\x18\x01 \x01(\t\x12\x0f\n\x07sucesso\x18\x02 \x01(\x08\"N\n\x0f\x43onsultaRequest\x12\x0c\n\x04sala\x18\x01 \x01(\t\x12-\n\tdata_hora\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"7\n\x10\x43onsultaResponse\x12\x10\n\x08mensagem\x18\x01 \x01(\t\x12\x11\n\treservada\x18\x02 \x01(\x08\"\x1b\n\x0bSalaRequest\x12\x0c\n\x04sala\x18\x01 \x01(\t\"(\n\x14ReservasSalaResponse\x12\x10\n\x08usuarios\x18\x01 \x03(\t\"!\n\x0eUsuarioRequest\x12\x0f\n\x07usuario\x18\x01 \x01(\t\"G\n\x17ReservasUsuarioResponse\x12,\n\x08reservas\x18\x01 \x03(\x0b\x32\x1a.reservassalas.ReservaInfo\"J\n\x0bReservaInfo\x12\x0c\n\x04sala\x18\x01 \x01(\t\x12-\n\tdata_hora\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp2\xc4\x03\n\x0cReservaSalas\x12Q\n\x10\x43\x61\x64\x61strarReserva\x12\x1d.reservassalas.ReservaRequest\x1a\x1e.reservassalas.ReservaResponse\x12O\n\x0eRemoverReserva\x12\x1d.reservassalas.ReservaRequest\x1a\x1e.reservassalas.ReservaResponse\x12S\n\x10\x43onsultarReserva\x12\x1e.reservassalas.ConsultaRequest\x1a\x1f.reservassalas.ConsultaResponse\x12X\n\x15\x43onsultarReservasSala\x12\x1a.reservassalas.SalaRequest\x1a#.reservassalas.ReservasSalaResponse\x12\x61\n\x18\x43onsultarReservasUsuario\x12\x1d.reservassalas.UsuarioRequest\x1a&.reservassalas.ReservasUsuarioResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'reservasalas_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RESERVAREQUEST']._serialized_start=70
  _globals['_RESERVAREQUEST']._serialized_end=164
  _globals['_RESERVARESPONSE']._serialized_start=166
  _globals['_RESERVARESPONSE']._serialized_end=218
  _globals['_CONSULTAREQUEST']._serialized_start=220
  _globals['_CONSULTAREQUEST']._serialized_end=298
  _globals['_CONSULTARESPONSE']._serialized_start=300
  _globals['_CONSULTARESPONSE']._serialized_end=355
  _globals['_SALAREQUEST']._serialized_start=357
  _globals['_SALAREQUEST']._serialized_end=384
  _globals['_RESERVASSALARESPONSE']._serialized_start=386
  _globals['_RESERVASSALARESPONSE']._serialized_end=426
  _globals['_USUARIOREQUEST']._serialized_start=428
  _globals['_USUARIOREQUEST']._serialized_end=461
  _globals['_RESERVASUSUARIORESPONSE']._serialized_start=463
  _globals['_RESERVASUSUARIORESPONSE']._serialized_end=534
  _globals['_RESERVAINFO']._serialized_start=536
  _globals['_RESERVAINFO']._serialized_end=610
  _globals['_RESERVASALAS']._serialized_start=613
  _globals['_RESERVASALAS']._serialized_end=1065
# @@protoc_insertion_point(module_scope)
